#!/usr/bin/env bash

set -e

if ! command -v "inferno-collapse-perf" &> /dev/null; then
  cargo install inferno
fi

RUSTFLAGS="-g" cargo \
  +stable \
  build \
  --bin s2n-quic-qns \
  --release

cd ./scripts/server-perf/client
cargo +stable build --release
cd ../../../

