#!/usr/bin/env bash

set -e

if ! command -v "inferno-collapse-perf" &> /dev/null; then
  cargo install inferno
fi

RUSTFLAGS="-g -Ctarget-cpu=native" cargo \
  +stable \
  build \
  --bin s2n-quic-qns \
  --release

cd ./scripts/server-perf/client
RUSTFLAGS="-Ctarget-cpu=native" cargo +stable build --release
cd ../../../

