#!/usr/bin/env bash

set -e

SIZE=${1:-1G}

DIR=$(mktemp -d -t s2n-quic-perf-XXXXXXXXXX)

./scripts/server-perf/build

mkdir -p ./target/perf
if [ ! -f "./target/perf/$SIZE.img" ]; then
  fallocate -l "$SIZE" "$DIR/$SIZE.img"
fi

sudo sh -c "perf record \
  --output $DIR/$SIZE.perf \
  --call-graph dwarf \
 ./target/release/s2n-quic-qns \
  interop \
  server \
  --port 4433 \
  --www-dir $DIR" &
SUDO_PID=$!

function stop_server() {
  SHELL_PID=$(ps --ppid $SUDO_PID -o pid=)
  PERF_PID=$(ps --ppid $SHELL_PID -o pid=)
  sudo kill -SIGINT $PERF_PID

  rm -f "$DIR/$SIZE.img"

  wait $SUDO_PID || true
  if [ ! -z "$1" ]; then
    echo $1
    exit 1
  fi
}

echo "waiting for server to boot"
sleep 3

echo "executing request"
./scripts/server-perf/client/target/release/perf-client \
  https://localhost:4433/$SIZE.img || stop_server "failed to finish the request"

sleep 1
stop_server

sudo perf script \
  --input $DIR/$SIZE.perf \
  2>/dev/null \
  | inferno-collapse-perf \
  > $DIR/$SIZE.folded

cat $DIR/$SIZE.folded \
  | inferno-flamegraph \
  > ./target/perf/$SIZE.svg

sudo rm -f $DIR/$SIZE.perf
sudo rm -f $DIR/$SIZE.folded

echo "flamegraph available in ./target/perf/$SIZE.svg"
