#!/usr/bin/env bash

set -e

./scripts/server-perf/run 1000MB 0GB
# ./scripts/server-perf/run 750MB 250MB
# ./scripts/server-perf/run 500MB 500MB
# ./scripts/server-perf/run 250MB 750MB
./scripts/server-perf/run 0MB 1000MB

OUT=./target/perf

# Generate an html file with a directory listing of all flamegraphs. -I is used to exclude
# html files so index.html itself doesn't show up in the output.
tree -H "." -L 1 -T "Performance Simulations" --noreport --charset utf-8 -I "*.html" > index.html
