#!/usr/bin/env bash

set -e

./scripts/server-perf/run 1000MB 0GB
# ./scripts/server-perf/run 750MB 250MB
# ./scripts/server-perf/run 500MB 500MB
# ./scripts/server-perf/run 250MB 750MB
./scripts/server-perf/run 0MB 1000MB

OUT=./target/perf
tree -H "." -L 1 -T "PERFORMANCE Simulations" --noreport --charset utf-8 -I "*.html" > $OUT/index.html
