#!/usr/bin/env bash

set -e

SIZE=${1:-1G}

DIR=$(mktemp -d -t s2n-quic-perf-XXXXXXXXXX)

mkdir -p ./target/perf

perf record \
  --output $DIR/$SIZE.perf \
  --call-graph dwarf \
  --event cycles \
  -- \
  ./target/release/s2n-quic-qns \
  perf \
  server \
  --connections 1 \
  --port 4433 &
PERF_PID=$!

function stop_server() {
  echo "shutting down server"
  kill $PERF_PID
  echo $1
  exit 1
}

echo "waiting for server to boot"
sleep 3

echo "executing request"
./scripts/server-perf/client/target/release/perf-client \
  https://localhost:4433 --download $SIZE || stop_server "failed to finish the request"

echo "waiting for server to shut down"
wait $PERF_PID

echo "folding events"
perf script \
  --input $DIR/$SIZE.perf \
  2>/dev/null \
  | inferno-collapse-perf \
  > $DIR/$SIZE.folded

echo "generating flamegraph"
inferno-flamegraph $DIR/$SIZE.folded \
  --title $SIZE \
  > ./target/perf/$SIZE.svg

rm -rf $DIR

echo "flamegraph available in ./target/perf/$SIZE.svg"
