// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

//! Transmission packets that are generated by the application layer.
//!
//! Applications create transmissions (datagrams or control packets) with routing info
//! and packet-specific data, but without encryption or packet numbers. Socket workers
//! complete these by:
//! 1. Looking up or deriving the peer-specific crypto state
//! 2. Assigning the next packet number (nonce)
//! 3. Encrypting the payload with the peer's current credentials
//! 4. Adding the source control port from the worker's socket
//!
//! This design keeps the hot path in socket workers simple by having the
//! application pre-compute the path secret map entry, avoiding map lookups
//! on every packet send.

use s2n_quic_core::varint::VarInt;

use super::{HeaderLen, PayloadLen, RoutingInfo};
use crate::{
    byte_vec::ByteVec, congestion, credentials::Credentials,
    path::secret::map::Entry as PathSecretEntry,
};
use std::sync::Arc;

/// Maximum datagram header overhead to reserve from MTU for payload capacity.
///
/// This is a conservative estimate assuming all VarInts take maximum space (8 bytes).
/// Applications constructing PartialDatagrams don't know what values will be chosen
/// by the pipeline (e.g., packet_number, source_sender_id), so we must assume worst-case.
///
/// Header structure:
/// - Tag: 1 byte
/// - Credentials ID: 16 bytes (zerocopy, fixed size)
/// - Key ID (part of credentials): 8 bytes
/// - Wire version: 1 byte (always ZERO = 1 byte VarInt)
/// - Source control port: 2 bytes
/// - Packet number: 8 bytes (max VarInt)
/// - Routing info (FlowData with max VarInts):
///   - Type tag: 1 byte
///   - source_sender_id: 8 bytes
///   - queue_pair (2 VarInts): 16 bytes
///   - stream_id: 8 bytes
///   - offset: 8 bytes
///   = 41 bytes
/// - Payload length: 8 bytes (max VarInt)
/// - App header length: 8 bytes (conservative, may not be present)
/// - Crypto tag: 16 bytes (AES-GCM tag size)
///
/// Total: 1 + 16 + 8 + 1 + 2 + 8 + 41 + 8 + 8 + 16 = 109 bytes
pub const MAX_FLOW_DATA_HEADER_OVERHEAD: u16 = 109;

/// Type of packet being transmitted
#[derive(Clone, Debug)]
pub enum PacketType {
    /// Datagram packet with application header and payload
    Datagram {
        /// Routing information for the packet
        routing_info: RoutingInfo,
        /// Application header data (encrypted with payload if present)
        header: ByteVec,
        /// Application payload data
        payload: ByteVec,
    },
    /// Control packet with control frames (e.g., ACKs)
    Control {
        /// Routing information for control packets
        routing_info: crate::packet::control::RoutingInfo,
        /// Encoded control frames
        control_data: ByteVec,
    },
}

/// Completion notification channel for transmissions
pub type CompletionSender =
    crate::socket::channel::intrusive_queue::datagram_completion::Sender<PartialDatagram>;

/// Status of a datagram transmission
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransmissionStatus {
    /// Datagram is pending transmission
    Pending,
    /// The datagram was acknowledged by the peer
    Acknowledged,
    /// The datagram failed to be delivered
    Failed(FailureReason),
}

/// Reasons why a datagram might fail to be delivered
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FailureReason {
    /// The peer was declared dead (PTO reached max idle time)
    PeerDead,
    /// Transmission error (peer active but refused packet)
    TransmissionError,
    /// Unknown path secret (path secret refused by peer, flow reset)
    UnknownPathSecret,
    /// The sender was dropped and requested cancellation
    Cancelled,
}

impl Default for TransmissionStatus {
    fn default() -> Self {
        Self::Pending
    }
}

/// Transmission metadata tracked for each packet
#[derive(Debug, Clone, Copy)]
pub struct TransmissionInfo {
    /// Congestion control information captured at send time
    pub cc_info: congestion::PacketInfo,
    /// Time the packet was transmitted
    pub time_sent: s2n_quic_core::time::Timestamp,
    /// Number of bytes sent (packet size)
    pub sent_bytes: u16,
}

/// Transmission packet constructed by the application.
///
/// Contains all application-layer information needed to construct a packet (datagram or control),
/// but lacks encryption, packet numbering, and source control port which will be added by socket workers.
///
/// The same Entry<PartialDatagram> moves through different intrusive queues during
/// its lifecycle (transmission wheel, completion queue, etc.) without boxing/unboxing.
#[derive(Clone)]
pub struct PartialDatagram {
    /// Type of packet and its type-specific data (includes routing info)
    pub packet_type: PacketType,
    /// Path secret entry for the destination peer
    ///
    /// Pre-computed by the application to avoid map lookups in socket workers.
    /// Workers will derive peer-specific crypto state from this entry.
    pub path_secret_entry: Arc<PathSecretEntry>,
    /// Current transmission status (updated by socket workers)
    pub status: TransmissionStatus,
    /// Completion notification sender (if the application wants notification)
    pub completion: Option<CompletionSender>,
    /// Transmission metadata (populated when packet is sent)
    pub transmission_info: Option<TransmissionInfo>,
}

impl std::fmt::Debug for PartialDatagram {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PartialDatagram")
            .field("packet_type", &self.packet_type)
            .field("path_secret", self.path_secret_entry.id())
            .field("status", &self.status)
            .field("completion", &self.completion)
            .field("transmission_info", &self.transmission_info)
            .finish()
    }
}

impl PartialDatagram {
    /// Creates a new datagram transmission.
    #[inline]
    pub fn new_datagram(
        routing_info: RoutingInfo,
        header: ByteVec,
        payload: ByteVec,
        path_secret_entry: Arc<PathSecretEntry>,
        completion: Option<CompletionSender>,
    ) -> Self {
        Self {
            packet_type: PacketType::Datagram {
                routing_info,
                header,
                payload,
            },
            path_secret_entry,
            status: TransmissionStatus::Pending,
            completion,
            transmission_info: None,
        }
    }

    /// Creates a new control packet transmission.
    #[inline]
    pub fn new_control(
        routing_info: crate::packet::control::RoutingInfo,
        control_data: ByteVec,
        path_secret_entry: Arc<PathSecretEntry>,
    ) -> Self {
        Self {
            packet_type: PacketType::Control {
                routing_info,
                control_data,
            },
            path_secret_entry,
            status: TransmissionStatus::Pending,
            completion: None, // Control packets don't need completion notifications
            transmission_info: None,
        }
    }

    /// Returns the remote address for this datagram
    #[inline]
    pub fn remote_address(&self) -> std::net::SocketAddr {
        self.path_secret_entry.data_addr()
    }

    /// Returns the routing info for datagram packets, or None for control packets
    #[inline]
    pub fn datagram_routing_info(&self) -> Option<&RoutingInfo> {
        match &self.packet_type {
            PacketType::Datagram { routing_info, .. } => Some(routing_info),
            PacketType::Control { .. } => None,
        }
    }

    /// Returns the routing info for control packets, or None for datagram packets
    #[inline]
    pub fn control_routing_info(&self) -> Option<&crate::packet::control::RoutingInfo> {
        match &self.packet_type {
            PacketType::Control { routing_info, .. } => Some(routing_info),
            PacketType::Datagram { .. } => None,
        }
    }

    /// Returns the mutable routing info for control packets
    #[inline]
    pub fn control_routing_info_mut(&mut self) -> Option<&mut crate::packet::control::RoutingInfo> {
        match &mut self.packet_type {
            PacketType::Control { routing_info, .. } => Some(routing_info),
            PacketType::Datagram { .. } => None,
        }
    }

    /// Returns the sticky sender_id if this datagram requires routing to a specific send socket.
    #[inline]
    pub fn sticky_sender_id(&self) -> Option<s2n_quic_core::varint::VarInt> {
        match &self.packet_type {
            PacketType::Datagram { routing_info, .. } => {
                if routing_info.requires_sticky_sender_id() {
                    routing_info.source_sender_id()
                } else {
                    None
                }
            }
            PacketType::Control { routing_info, .. } => {
                if routing_info.requires_sticky_sender_id() {
                    routing_info.source_sender_id()
                } else {
                    None
                }
            }
        }
    }

    /// Estimates the final encoded packet size including crypto overhead.
    #[inline]
    pub fn estimate_encoded_len(&self, crypto_tag_len: usize) -> usize {
        match &self.packet_type {
            PacketType::Datagram {
                routing_info,
                header,
                payload,
            } => {
                let header_len =
                    HeaderLen::new(header.len() as u64).expect("header length fits in VarInt");
                let payload_len =
                    PayloadLen::new(payload.len() as u64).expect("payload length fits in VarInt");
                super::encoder::estimate_len(
                    super::PacketNumber::MAX, // Placeholder, actual value assigned by worker
                    *routing_info,
                    header_len,
                    payload_len,
                    crypto_tag_len,
                )
            }
            PacketType::Control {
                routing_info,
                control_data,
            } => {
                use s2n_quic_core::varint::VarInt;
                let control_data_len = VarInt::new(control_data.len() as u64)
                    .expect("control data length fits in VarInt");
                crate::packet::control::encoder::estimate_len(
                    VarInt::MAX, // Placeholder, actual value assigned by worker
                    None,        // source_queue_id
                    None,        // stream_id
                    *routing_info,
                    control_data_len,
                    crypto_tag_len,
                )
            }
        }
    }

    /// Encodes the transmission into the provided buffer.
    ///
    /// Returns the number of bytes written.
    #[inline]
    pub fn encode<Sealer>(
        &mut self,
        encoder_buf: s2n_codec::EncoderBuffer,
        source_control_port: u16,
        source_sender_id: VarInt,
        packet_number: VarInt,
        sealer: &Sealer,
        credentials: &Credentials,
        flow_attempt_id: &mut VarInt,
    ) -> usize
    where
        Sealer: crate::crypto::seal::Application,
    {
        match &mut self.packet_type {
            PacketType::Datagram {
                routing_info,
                header,
                payload,
            } => {
                routing_info.set_attempt_id(flow_attempt_id);
                let routing_info = routing_info.with_source_sender_id(source_sender_id);
                routing_info.before_encode();
                let header_len =
                    HeaderLen::new(header.len() as u64).expect("header length fits in VarInt");
                let payload_len =
                    PayloadLen::new(payload.len() as u64).expect("payload length fits in VarInt");

                let mut header_reader = header.reader();
                let mut payload_reader = payload.reader();

                super::encoder::encode(
                    encoder_buf,
                    source_control_port,
                    routing_info,
                    Some(packet_number),
                    header_len,
                    &mut header_reader,
                    payload_len,
                    &mut payload_reader,
                    sealer,
                    credentials,
                )
            }
            PacketType::Control {
                routing_info,
                control_data,
            } => {
                let routing_info = routing_info.with_source_sender_id(source_sender_id);
                use s2n_quic_core::varint::VarInt;
                let control_data_len = VarInt::new(control_data.len() as u64)
                    .expect("control data length fits in VarInt");

                let mut control_data_reader = control_data.reader();

                crate::packet::control::encoder::encode_with_application(
                    encoder_buf,
                    None, // source_queue_id
                    None, // stream_id
                    packet_number,
                    routing_info,
                    control_data_len,
                    &mut control_data_reader,
                    sealer,
                    credentials,
                )
            }
        }
    }
}

/// Builder for constructing transmissions (datagrams or control packets).
pub struct PartialDatagramBuilder {
    routing_info: RoutingInfo,
    header: ByteVec,
    payload: ByteVec,
    path_secret_entry: Option<Arc<PathSecretEntry>>,
    completion: Option<CompletionSender>,
}

impl PartialDatagramBuilder {
    /// Creates a new builder with best-effort delivery (no completion notification).
    #[inline]
    pub fn new() -> Self {
        Self {
            routing_info: RoutingInfo::None,
            header: ByteVec::new(),
            payload: ByteVec::new(),
            path_secret_entry: None,
            completion: None,
        }
    }

    /// Sets the routing information.
    #[inline]
    pub fn with_routing_info(mut self, routing_info: RoutingInfo) -> Self {
        self.routing_info = routing_info;
        self
    }

    /// Sets the complete header.
    #[inline]
    pub fn with_header(mut self, header: ByteVec) -> Self {
        self.header = header;
        self
    }

    /// Sets the complete payload.
    #[inline]
    pub fn with_payload(mut self, payload: ByteVec) -> Self {
        self.payload = payload;
        self
    }

    /// Sets the path secret entry.
    #[inline]
    pub fn with_path_secret_entry(mut self, entry: Arc<PathSecretEntry>) -> Self {
        self.path_secret_entry = Some(entry);
        self
    }

    /// Sets the completion strategy.
    #[inline]
    pub fn with_completion(mut self, completion: Option<CompletionSender>) -> Self {
        self.completion = completion;
        self
    }

    /// Builds a datagram transmission.
    ///
    /// Returns None if the path secret entry is not set.
    #[inline]
    pub fn build(self) -> Option<PartialDatagram> {
        Some(PartialDatagram::new_datagram(
            self.routing_info,
            self.header,
            self.payload,
            self.path_secret_entry?,
            self.completion,
        ))
    }
}

impl Default for PartialDatagramBuilder {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use bytes::Bytes;

    #[test]
    fn partial_datagram_builder() {
        let entry = PathSecretEntry::fake("127.0.0.1:8080".parse().unwrap(), None);

        let mut payload = ByteVec::new();
        payload.push_back(Bytes::from_static(b"test data"));

        let datagram = PartialDatagram::new_datagram(
            RoutingInfo::None,
            ByteVec::new(),
            payload.clone(),
            entry,
            None.into(), // No completion notification
        );

        if let PacketType::Datagram { payload: p, .. } = &datagram.packet_type {
            assert_eq!(p.len(), 9);
        } else {
            panic!("Expected datagram packet type");
        }
    }

    #[test]
    fn max_header_overhead_matches_estimate() {
        use s2n_quic_core::varint::VarInt;

        // Create worst-case routing info with maximum VarInts
        let routing_info = RoutingInfo::FlowData {
            source_sender_id: VarInt::MAX,
            queue_pair: crate::packet::datagram::routing_info::QueuePair {
                source_queue_id: VarInt::MAX,
                dest_queue_id: VarInt::MAX,
            },
            stream_id: VarInt::MAX,
            offset: VarInt::MAX,
            is_fin: false,
        };

        // Use u16::MAX for header and payload lengths (will never be bigger)
        let header_len = HeaderLen::new(u16::MAX as u64).unwrap();
        let payload_len = PayloadLen::new(u16::MAX as u64).unwrap();

        // Estimate with worst-case packet number and crypto tag
        let estimated = super::super::encoder::estimate_len(
            super::super::PacketNumber::MAX,
            routing_info,
            header_len,
            payload_len,
            16, // AES-GCM tag size
        );

        // The estimate minus actual payload and header should exactly match MAX_HEADER_OVERHEAD
        let overhead = estimated - u16::MAX as usize - u16::MAX as usize;
        assert_eq!(
            overhead,
            MAX_FLOW_DATA_HEADER_OVERHEAD as usize,
            "Estimated overhead {overhead} doesn't match MAX_HEADER_OVERHEAD {MAX_FLOW_DATA_HEADER_OVERHEAD}"
        );
    }

    // TODO: Add test that verifies the actual encode output matches estimate_len
    // for worst-case routing info with maximum VarInts. This requires setting up
    // crypto/sealing infrastructure.
}
