#!/usr/bin/env bash

set -e

INTEROP_DIR=target/quic-interop-runner

# Setup the s2n-quic docker image
sudo docker build . --file quic/s2n-quic-qns/etc/Dockerfile.build --tag awslabs/s2n-quic-qns

if [ ! -d $INTEROP_DIR ]; then
  git clone https://github.com/marten-seemann/quic-interop-runner $INTEROP_DIR
  # make sure to keep this up to date with the interop workflow
  cd $INTEROP_DIR
  git checkout 7221a219e9a0070bfd82b23bdfde3d1b56a7b6a5
  git apply --3way ../../.github/interop/runner.patch
  cd ../../
fi

if [ ! -d $INTEROP_DIR/.venv ]; then
  cd $INTEROP_DIR
  python3 -m venv .venv
  source .venv/bin/activate
  pip install --upgrade pip
  pip install wheel
  cd ../../
fi

function ensure_executable() {
  if ! command -v $1 &> /dev/null; then
    echo "$1 needs to be installed"
    exit
  fi
}

ensure_executable "docker-compose"
ensure_executable "tshark"

case "$(uname -s)" in
   Linux)
     sudo modprobe ip6table_filter
     ;;
   *)
     # TODO possibly add other things for Darwin
     ;;
esac

cd $INTEROP_DIR
source .venv/bin/activate
pip install --upgrade -r requirements.txt

case "$@" in
   pull)
     python pull.py
     exit 0
     ;;
   *)
     # continue
     ;;
esac

python run.py --server s2n-quic --debug "$@"
