#!/usr/bin/env bash

set -eo pipefail

WORKLOAD=${1:-tiny-bidi}
DURATION=${2:-}
PROFILE=${3:-release-debug}

ARGS="--config xtask/etc/local.toml --servers 1 --clients 1 --profile ${PROFILE} --workloads ${WORKLOAD}"

if [ -n "${DURATION}" ]; then
    ARGS="${ARGS} --timeout ${DURATION}"
fi

RUST_BACKTRACE=1 cargo xtask local ${ARGS}
