#!/usr/bin/env bash

#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -e

# can be run for specific toolchain: `./scripts/test_no_std nightly-2021-06-21`
TOOLCHAIN=${1:-nightly}

cargo +$TOOLCHAIN build --package=s2n-quic-core -Zbuild-std=core --no-default-features --target=bpfel-unknown-none
