#!/usr/bin/env bash

#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -e

if ! command -v "inferno-collapse-perf" &> /dev/null; then
  cargo install inferno
fi

if [ ! -f target/perf/quinn/bin/perf_client ]; then
  mkdir -p target/perf/quinn
  cargo +stable install \
    --git https://github.com/quinn-rs/quinn \
    --rev 730fdaf723eef125c175fbcdba1ac3fe3324f7ce \
    --bin perf_client \
    --root target/perf/quinn \
    --target-dir target/perf/quinn \
    perf
fi

RUSTFLAGS="-g" cargo \
  +stable \
  build \
  --bin s2n-quic-qns \
  --release

