#!/usr/bin/env bash

#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -e

if ! command -v "inferno-collapse-perf" &> /dev/null; then
  cargo install inferno
fi

if ! command -v "ultraman" &> /dev/null; then
  cargo install ultraman
fi

if [ ! -f target/perf/quinn/bin/perf_client ] || [ ! -f target/perf/quinn/bin/perf_server ]; then
  mkdir -p target/perf/quinn
  cargo +stable install \
    --git https://github.com/quinn-rs/quinn \
    --rev 7b4b4c31e5878bdbce56ab2737dd8cfbafe1c4db \
    --bin perf_client \
    --bin perf_server \
    --root target/perf/quinn \
    --target-dir target/perf/quinn \
    perf
fi

RUSTFLAGS="-g" cargo \
  +stable \
  build \
  --bin s2n-quic-qns \
  --release
