#!/usr/bin/env bash

#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -e

./scripts/perf/build

# allow running perf without sudo
if [ -f /proc/sys/kernel/perf_event_paranoid ]; then
    sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'
fi

./scripts/perf/test $@
