#!/usr/bin/env bash

#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -e

./scripts/perf/build

sudo env PATH="$PATH" ./scripts/perf/test $@
